### ISSUE TITLE
Animation is always on top

### ISSUE THREAD

**Issue by teshlya** [saket/InboxRecyclerView#14]
What I did wrong is that my animation is always on top, not from item of recyclerview?
https://drive.google.com/open?id=1WoHwzns25zw7JbkpoBVmlML6FPBuss9Y

`public class MainActivity extends AppCompatActivity {

    ExpandablePageLayout expandablePageLayout;
    InboxRecyclerView recyclerView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        recyclerView = findViewById(R.id.rv);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        expandablePageLayout = findViewById(R.id.inbox_email_thread_page);

        recyclerView.setExpandablePage(expandablePageLayout);
        recyclerView.setTintPainter(new CompleteListTintPainter(Color.WHITE, 0.65F));
        recyclerView.setAdapter(new MyAdapter(recyclerView));

    }

    @Override
    public void onBackPressed() {
        if (expandablePageLayout.isExpandedOrExpanding()) {
            recyclerView.collapse();
        } else {
            super.onBackPressed();
        }
    }
}

public class MyAdapter extends RecyclerView.Adapter<MyAdapter.Holder> {
    Context context;
    InboxRecyclerView recyclerView;

    public MyAdapter(InboxRecyclerView recyclerView) {
        setHasStableIds(true);
        this.recyclerView = recyclerView;
    }

    @NonNull
    @Override
    public Holder onCreateViewHolder(@NonNull ViewGroup viewGroup, int i) {
        context = viewGroup.getContext();
        return new Holder(LayoutInflater.from(viewGroup.getContext())
                .inflate(R.layout.item, viewGroup, false));
    }

    @Override
    public void onBindViewHolder(@NonNull Holder holder, int i) {
        holder.bind(i);
    }

    @Override
    public int getItemCount() {
        return 10;
    }

    class Holder extends RecyclerView.ViewHolder{

        FrameLayout frameLayout;

        public Holder(@NonNull View itemView) {
            super(itemView);
            frameLayout = itemView.findViewById(R.id.click);
        }

        public void bind(final int pos) {
            frameLayout.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(final View v) {
                    recyclerView.expandItem(pos);

                }
            });
        }
    }
}

<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <me.saket.inboxrecyclerview.InboxRecyclerView
        android:id="@+id/rv"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipToPadding="false"
        android:background="#ffffff"/>

    <me.saket.inboxrecyclerview.page.ExpandablePageLayout
        android:id="@+id/inbox_email_thread_page"
        android:background="#000000"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</androidx.coordinatorlayout.widget.CoordinatorLayout>

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/click"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="center_horizontal">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:paddingVertical="18dp"
        android:text="123456" />
</FrameLayout>

`

**Comment by saket** [comment]
@teshlya your adapter isn't providing IDs for the list items, despite using `setHasStableIds(true)`. `InboxRecyclerView` relies on IDs to uniquely identify items. The default implementation of `getItemId()` returns `NO_ID` so all your items are treated as the same.

**Comment by teshlya** [comment]
Thank you very much. Everything works fine. How can I set duration animation, slow speed?

**Comment by saket** [comment]
Whoops, completely forgot to document them. I've updated the wiki: https://github.com/saket/InboxRecyclerView/wiki/Item-animations

Thanks!

**Comment by teshlya** [comment]
Thanks. Very good library. I have one more question. Is it possible to go for example -  recyclerView.expandItem(5), but return to position - 7?

**Comment by saket** [comment]
Hrm, not sure if it'll work as expected, but you can try setting `inboxRecyclerView.expandedItem` manually. What's the use case for this?

**Comment by teshlya** [comment]
How can I set duration for activity - expandFromTop() or expandFrom(). And how can I set setPullToCollapseEnabled(false) for activity?

**Comment by saket** [comment]
There's no way right now. I'll expose the underlying `ExpandablePageLayout` in a future release to make that happen.

**Comment by teshlya** [comment]
Thanks. Notify me in comments when it well be ready, please

**Comment by teshlya** [comment]
Hello. How to remove item from recyclerview?

` @Override
        public void onSwiped(RecyclerView.ViewHolder viewHolder, int swipeDir) {
            int position = viewHolder.getAdapterPosition();
            articles.remove(position);
            notifyDataSetChanged();
        }`

if this code, then I have a white empty space. Video - https://drive.google.com/file/d/1nnJ3AXXailegOfxaYb-cykoOs72A3oZ0/view

`     @Override
            public void onSwiped(RecyclerView.ViewHolder viewHolder, int swipeDir) {
                int position = viewHolder.getAdapterPosition();
                articles.remove(position);
                notifyItemRemoved(position);
            }`

if this code, then I have error if position - 0. Video - https://drive.google.com/file/d/13W2CnKzdIYUlqes5HojwMwIC-57kKxSo/view

`java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:-1).state:25 me.saket.inboxrecyclerview.InboxRecyclerView{48c7ea0 VFED..... .F....ID 0,0-1440,2448 #7f090038 app:id/community_recycler_view}, adapter:teshlya.com.reddit.adapter.CommunityAdapter@239767f, layout:androidx.recyclerview.widget.LinearLayoutManager@9cc564c, context:teshlya.com.reddit.screen.ArticleActivity@9771922
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5923)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:622)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3639)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)`

**Comment by teshlya** [comment]
Hello. How remove item from recyclerview?

`     @Override
            public void onSwiped(RecyclerView.ViewHolder viewHolder, int swipeDir) {
                int position = viewHolder.getAdapterPosition();
                articles.remove(position);
                notifyDataSetChanged();
            }`

If this code, then I have white empty space. Video - https://drive.google.com/file/d/1nnJ3AXXailegOfxaYb-cykoOs72A3oZ0/view

`     @Override
            public void onSwiped(RecyclerView.ViewHolder viewHolder, int swipeDir) {
                int position = viewHolder.getAdapterPosition();
                articles.remove(position);
                notifyItemRemoved(position);
            }`

If this code, then I have error on position - 0. Video - https://drive.google.com/file/d/1nnJ3AXXailegOfxaYb-cykoOs72A3oZ0/view

`java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:-1).state:25 me.saket.inboxrecyclerview.InboxRecyclerView{48c7ea0 VFED..... .F....ID 0,0-1440,2448 #7f090038 app:id/community_recycler_view}, adapter:teshlya.com.reddit.adapter.CommunityAdapter@239767f, layout:androidx.recyclerview.widget.LinearLayoutManager@9cc564c, context:teshlya.com.reddit.screen.ArticleActivity@9771922
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5923)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:622)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)`

**Comment by teshlya** [comment]
b

**Comment by teshlya** [comment]
Hello. How remove item from recyclerview?

`     @Override
            public void onSwiped(RecyclerView.ViewHolder viewHolder, int swipeDir) {
                int position = viewHolder.getAdapterPosition();
                articles.remove(position);
                notifyDataSetChanged();
            }`

If this code, then I have white empty space. Video - https://drive.google.com/file/d/1nnJ3AXXailegOfxaYb-cykoOs72A3oZ0/view

`     @Override
            public void onSwiped(RecyclerView.ViewHolder viewHolder, int swipeDir) {
                int position = viewHolder.getAdapterPosition();
                articles.remove(position);
                notifyItemRemoved(position);
            }`

If this code, then I have error on position - 0. Video - https://drive.google.com/file/d/1nnJ3AXXailegOfxaYb-cykoOs72A3oZ0/view

`java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:-1).state:25 me.saket.inboxrecyclerview.InboxRecyclerView{48c7ea0 VFED..... .F....ID 0,0-1440,2448 #7f090038 app:id/community_recycler_view}, adapter:teshlya.com.reddit.adapter.CommunityAdapter@239767f, layout:androidx.recyclerview.widget.LinearLayoutManager@9cc564c, context:teshlya.com.reddit.screen.ArticleActivity@9771922
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5923)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:622)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3875)`

**Comment by saket** [comment]
This does not sound related to `InboxRecyclerView`. Does this work with a normal `RecyclerView`?

Edit: can you create a separate issue for this? Dumping all answers in a single issue will not help others.

**Comment by teshlya** [comment]
`@Override public void onSwiped(RecyclerView.ViewHolder viewHolder, int swipeDir) { int position = viewHolder.getAdapterPosition(); articles.remove(position); notifyDataSetChanged(); }`

This work good with RecyclerView, but with InboxRecyclerView I have empty white space - https://drive.google.com/file/d/1nnJ3AXXailegOfxaYb-cykoOs72A3oZ0/view

**Comment by saket** [comment]
> can you create a separate issue for this?

**Comment by MuriloCalegari** [comment]
Hi @saket, how should I implement getItemID? Can't the position be the item's own id?

**Comment by MuriloCalegari** [comment]
I got it working now, I actually misunderstood expandItem(), now I'm just using position as the parameter for expandItem() and got getItemId() to return the position.

**Comment by saket** [comment]
@MuriloCalegari 🙂:+1:
