### ISSUE TITLE
Issues with InboxRecyclerView inside NestedScrollView

### ISSUE THREAD

**Issue by andyburris** [saket/InboxRecyclerView#19]
When the InboxRecyclerView is inside a NestedScrollView, there are lots of issues, such as the ExpandablePage expanding from farther down the list than wanted, and the items all being pushed down and replaced with blanks. Not sure if it's inherent to the NestedScrollView but it wasn't happening with regular RecyclerView.

**Comment by saket** [comment]
@andb3 this will be fun to debug at. Can I ask you to fork this project and update the sample app to reproduce this problem?

**Comment by andb3** [comment]
Yeah, I'll upload it when I get home.

**Comment by andyburris** [comment]
Ok, it's up at https://github.com/andb3/InboxRecyclerViewSample and the issue reproduces on the new sample

**Comment by saket** [comment]
Thanks @andb3. I'll try taking a look this weekend.

**Comment by andyburris** [comment]
Hey @saket, I made some changes in my local repository and I think I got it working with a custom ItemExpandAnimator. 
The only difference otherwise is some added logic in the expandItem and alignItemWithExpandingItem functions to see if there is scroll offset needed due to the NestedScrollView. 
If you want to take a look, it's in the `fix` branch in my repository

**Comment by saket** [comment]
I haven't been able to take a look at this. Considering that you've already found a fix, do you want to send a PR?

**Comment by andyburris** [comment]
Sure, let me fix a few issues I've found and I'll make one

**Comment by saket** [comment]
Sure 👍

**Comment by China77** [comment]
please fix the bug: inbox for  androidx.core.widget.NestedScrollView ,thx!

**Comment by China77** [comment]
https://github.com/googlesamples/android-ConstraintLayoutExamples+NestedScrollView is OK, it replace AppLayoutToolBar+NestedScrollView

**Comment by saket** [comment]
A bit late, but this should be solved with v3.0.0 that brings support for nested scrolling: https://github.com/saket/InboxRecyclerView/releases/tag/v3.0
