### ISSUE TITLE
Ongoing Toolbar animation cannot be stopped and app crashes if you exit

### ISSUE THREAD

**Issue by qwertyway** [saket/InboxRecyclerView#20]
If your app has a toolbar and you've set it for ExpandablePageLayout, after pressing Back quickly twice the app will crash (first back to start collapse, second to finish the app). At least any way to cancel animation would be cool (stopAnyOngoingPageAnimation() in ExpandablePageLayout now has an 'internal' visibility)

**Comment by saket** [comment]
I'll try investigating this this week

**Comment by saket** [comment]
This should be fixed in the next release. Sorry this only took me half a year to fix. I was fully occupied with moving to a new country, new job and a new home.
