### ISSUE TITLE
can not expand the class InboxRecyclerView

### ISSUE THREAD

**Issue by teshlya** [saket/InboxRecyclerView#22]
My app has a Toolbar with ` app: layout_scrollFlags = "scroll | enterAlways` and the animation overscroll in InboxRecyclerView is missing. I want to fix it like this - https://stackoverflow.com/questions/32667237/lollipop-appbarlayout-toolbar-missing-overscroll-animation, but I can not expand the class - "can not inherit from final me.saket.inboxrecyclerview.InboxRecyclerView"

**Comment by saket** [comment]
Hrm. Agreed. I should make `InboxRecyclerView` and related classes open so that they can be extended for custom behavior. Can you send a PR?

**Comment by teshlya** [comment]
What does this mean - PR, because my english is bad

**Comment by saket** [comment]
PR stands for Pull Request. If you have never submitted one before, doing one for `InboxRecyclerView` would be a great start. [This article](https://codeburst.io/a-step-by-step-guide-to-making-your-first-github-contribution-5302260a2940) might help. :)

**Comment by saket** [comment]
Should be fixed in the next release.
