### ISSUE TITLE
Collapsing won't work when battery saving is enabled

### ISSUE THREAD

**Issue by MuriloCalegari** [saket/InboxRecyclerView#25]
Hi,

I've noticed that if the system is in battery saving mode (Android default one, Samsung one didn't affect this) the page won't collapse, as you can see in this vídeo:

[youtu.be/iCS-hlQqods](https://youtu.be/iCS-hlQqods)

**Comment by MuriloCalegari** [comment]
I can see that some animations in other libraries are just being skippedg, so I believe that battery saving disables them and breaks InboxRecyclerView...

**Comment by MuriloCalegari** [comment]
Found this warning on Logcat that only appears when battery saving mode is enabled:

> W/OpenGLRenderer: Incorrectly called buildLayer on View: ExpandablePageLayout, destroying layer...

**Comment by MuriloCalegari** [comment]
Hi, @saket, is there a possibility to fix this? Apparently batter saving mode disable some logic around ObjectAnimator and ValueAnimator...

**Comment by MuriloCalegari** [comment]
Apparently some people were able to fix this by wrapping animations inside runnables, as seen here:

https://stackoverflow.com/questions/42523546/how-to-play-animations-in-battery-saver-mode-in-android-is-there-any-work-arou

https://stackoverflow.com/questions/36548097/object-animator-not-working-in-battery-saver-mode-post-jellybeanandroid-5-x

**Comment by saket** [comment]
Sorry for taking so long to respond. I was moving to a new country, new job and a new home. This should be fixed in the next release
