### ISSUE TITLE
RelativeLayout???

### ISSUE THREAD

**Issue by brh** [saket/InboxRecyclerView#3]
Like the library, will redo my app to use this (hopefully I finish this).  But why did you choose to use RelativeLayout as the super class for BaseExpandablePageLayout as opposed to ConstraintLayout?

**Comment by saket** [comment]
Good catch. There was no `ConstraintLayout` when I originally wrote this library. I think I should change it to `FrameLayout` and let users use `ConstraintLayout` or whatever they want as the top-level child.

**Comment by saket** [comment]
Closing this because I think it's too late to make this change now. Maybe I can fix this in a major version bump in the future.
