### ISSUE TITLE
How block dismiss inboxitem(rv) for only one direction 

### ISSUE THREAD

**Issue by dltxjsot123** [saket/InboxRecyclerView#38]
I want to implement close inboxlayout item for only one direction on specific condition.

I want to: 
If I add specific setting on inboxlayout code, Inboxlayout can be dismissed using onbackpressed 
 or  gesture.

**Comment by saket** [comment]
You can set an interceptor on your expandable page:

```kotlin
expandablePage.pullToCollapseInterceptor = { downX, downY, upwardPull ->
  if (isScrollAllowed(upwardPull)) IGNORED else INTERCEPTED
}
```

Full details can be found here in the wiki: https://github.com/saket/InboxRecyclerView/wiki/Pull-to-collapse
