### ISSUE TITLE
Support nested scrolling in ExpandablePageLayout

### ISSUE THREAD

**Issue by saket** [saket/InboxRecyclerView#4]
Listening to nested scrolling events would make it much easier to support scrollable child Views rather than asking users to manually do it by [intercepting pull-to-collapse gesture](https://github.com/saket/InboxRecyclerView/wiki/Pull-to-collapse).

**Comment by bernaferrari** [comment]
I am having this issue, where it doesn't scroll in certain cases. Is this the same issue?
![20190206_004722 2019-02-06 00_50_06](https://user-images.githubusercontent.com/351125/52317895-27798d00-29a9-11e9-8dd7-3d921684b156.gif)

**Comment by saket** [comment]
Yep. Nested scrolling can make that happen in a relatively easy manner.

**Comment by saket** [comment]
Released with v3.0: https://github.com/saket/InboxRecyclerView/releases/tag/v3.0
