### ISSUE TITLE
Support for non-androidx library

### ISSUE THREAD

**Issue by SahajRana** [saket/InboxRecyclerView#9]
Hi Saket, Its a wonderful library and I was hoping to use it for my project but to refactor to androidx is a major problem as most of the dependencies used are not currently using androidx and it is also unstable for production.

So, is there a workaround to keep using the support library without changing to androidx. Thanks!

**Comment by getsadzeg** [comment]
I don't think that this will/can be done.

**Comment by saket** [comment]
Thanks Sahaj. This is a very valid question and I couldn't come up with an easy solution. This is an unfortunate time for libraries where some apps have transitioned to `androidx` while some haven't. Considering that `androidx` is the way forward, I decided to stick with it.

> to refactor to androidx is a major problem as most of the dependencies used are not currently using androidx

This is actually not true. To help with this transition, Android Studio can automatically convert transitive dependencies to use androidx libraries. All you have to do is add these two lines to your `gradle.properties` file:

```groovy
android.useAndroidX=true
android.enableJetifier=true
```

More details about this here: [AndroidX Overview](https://developer.android.com/topic/libraries/support-library/androidx-overview)

> it is also unstable for production.

The timing on this is good. AndroidX has just hit stable version 1.0 so apps can now start using it.

Apparently, there's also a one-click option for migrating from support library to `androidx` as per the announcement blog post: [Hello World, AndroidX](https://android-developers.googleblog.com/2018/05/hello-world-androidx.html). Can you check if it works for you?

![refactor_to_androidx_menu_only](https://user-images.githubusercontent.com/2387680/45918179-ad84b380-bea0-11e8-851d-024ccfd4de29.png)

I've also considered splitting this project into two dependencies, something on the lines of:

```groovy
implementation 'me.saket:inboxrecyclerview:1.0.0'
implementation 'me.saket:inboxrecyclerview-recyclerview-support:1.0.0'
implementation 'me.saket:inboxrecyclerview-recyclerview-androidx:1.0.0'
```

I'm open to hearing more ideas.

**Comment by SahajRana** [comment]
This is all great, but I'm not so good at kotlin and have to give time to it to understand it more. 
What I have done now is, I have included your library in my project and changed it to Support library (spend half of day, fighting errors) and is good now, but.

**Could you please make a documentation or a walkthrough for integrating with Java?** That would be a great help! and if you want the support library integrated code, I'm happy to help!

**Comment by saket** [comment]
> (spend half of day, fighting errors)

Sounds like any other day in our lives

> walkthrough for integrating with Java?

I'm sorry, I do not understand what does that mean. Can you explain a bit more?

**Comment by SahajRana** [comment]
I meant like you have explained regarding Expanding Content,
![screenshot 299](https://user-images.githubusercontent.com/16938202/45919016-f6db0000-beac-11e8-896f-394167c594a7.png)

**It's not clear how would we add a fragment to the expandablePage.**

I saw the sample and you have done something like,
![screenshot 300](https://user-images.githubusercontent.com/16938202/45919052-82549100-bead-11e8-9140-2bc955708f6b.png)

It's not clear to me on how you have added fragment and called it through expandablePage and I'm not so good at kotlin, If you could provide a walkthrough regarding the implementation, that would be great!

**Comment by saket** [comment]
I'm sorry, but I cannot help you with that. The syntax isn't very different from Java, so I'm sure you'll figure it out. :) 

Feel free to reopen this issue if you have any questions specific to this project.

**Comment by SahajRana** [comment]
If you could let me know how to add a fragment to the `ExpandablePageLayout` that would be great, I couldn't find a method to do so.

**Comment by SahajRana** [comment]
Thanks, Saket for your patience. I now understood what you have done and it's working fine now. 

For future reference for others,

I was stuck at how to add `fragment` in `ExpandablePageLayout` but as the code snippet image provided above you can see that **fragment is inflated in the expandable view before calling onItemClickListener** and **ExpandablePageLayout handles the expansion of that fragment later on when you call onItemClickListener.** 

```` mExpandablePage=(ExpandablePageLayout)getActivity().findViewById(R.id.inbox_expand_page);
                mRecyclerView.setAdapter(adapter);
                mRecyclerView.setHasFixedSize(true);
                mRecyclerView.setNestedScrollingEnabled(false);

                SomeFragment frag = (SomeFragment) getActivity().getSupportFragmentManager().findFragmentById(mExpandablePage.getId());
                if (frag == null ) {
                    frag=new SomeFragment();
                }

                getActivity().getSupportFragmentManager().beginTransaction().replace(mExpandablePage.getId(),frag).commitNowAllowingStateLoss();

                mRecyclerView.setExpandablePage(mExpandablePage);
````


**One more trick,** If you want to put this expansion to a fragment which expands from Recyclerview of ViewPager then just put `inboxrecyclerview` in xml of fragment of that viewpager and  `ExpandablePageLayout` in xml of activity holding the viewpager and call

````mExpandablePage=(ExpandablePageLayout)getActivity().findViewById(R.id.inbox_expand_page);````

**Note that `getActivity()` is called not the `view` of fragment for Id.**

Thanks!

**Comment by saket** [comment]
Glad you were able to figure this out!
